### ISSUE TITLE
Remove failure?

### ISSUE THREAD

**Issue by Keats** [jcreekmore/pem-rs#18]
Hi,

Would a PR to remove the usage of failure be accepted? It pull `syn` and `quote` which are very heavy dependencies.

**Comment by jcreekmore** [comment]
Sure would. I was going to pull one in before, but that was right when the problem existed with the "new" Error backtrace bits.

**Comment by Keats** [comment]
I used the same PR as the base in https://github.com/jcreekmore/pem-rs/pull/19
What was the issue with the backtrace?

**Comment by jplatte** [comment]
This looks to be outdated.

**Comment by jcreekmore** [comment]
Sure is.
