### ISSUE TITLE
Any interest in serde support behind a feature flag?

### ISSUE THREAD

**Issue by tmpfs** [jcreekmore/pem-rs#33]
I have added the `Pem` type to an enum that was previously able to derive `Serialize` and `Deserialize` but I can no longer derive as `Pem` does not implement the serde traits.

Could we add this support behind a `serde` feature flag please? It should be quite straightforward I think given that `Pem` is just a couple of `String` values.

Happy to do the work if you would land this as it's quite tedious manually implementing the serde traits in my codebase on an enum with quite a few variants!

**Comment by jcreekmore** [comment]
I have no problem pulling in `serde` behind a feature flag. However, I think the `Pem` struct should `Serialize` to a `String` using the `encode` method and should `Deserialize` from a `String` using the `parse` method rather than just deriving the default implementations on the `Pem` struct.
